repos:
-   repo: https://github.com/Orest02/colornet
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: yapf
    -   id: mypy
        args: [--no-strict-optional]
    -   id: black
