version: "3"

services:
  api:
    restart: unless-stopped
    build: ./
    entrypoint:
      - newrelic-admin
      - run-program
    environment:
      NEW_RELIC_CONFIG_FILE: newrelic/newrelic.ini
      NEW_RELIC_APP_NAME: colornet-api-logs
    command: poetry run uvicorn --host 0.0.0.0 --port 5005 colornet.app.api:app
    ports:
      - 5005:5005
    networks:
      - test_network
  frontend:
    restart: unless-stopped
    build: ./
    entrypoint:
      - newrelic-admin
      - run-program
    environment:
      NEW_RELIC_CONFIG_FILE: newrelic/newrelic.ini
      NEW_RELIC_APP_NAME: colornet-frontend-logs
    command: poetry run streamlit run colornet/frontend/app.py --server.port 80 --server.address=127.0.0.1
    ports:
      - 80:80
    networks:
      - test_network
    depends_on:
      - api
  agent:
    container_name: newrelic-container-watch
    build:
      context: newrelic/
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

networks:
  test_network:
    driver: bridge
